### ISSUE TITLE
Checklist do Queimadas Frontend

### ISSUE THREAD

**Issue by luizlaljr** [luizlaljr/queimadasfrontend#1]
- [ ] Criar Header;

> - [ ] Criar a barra de Navegação;

- [ ] Criar Footer;

- [ ] Criar Router_Outlet;

- [ ] Criar o modulo do Mapa;

- [ ] Criar o módulo Áreas Protegidas
